/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { Mesh } from "three";
import { useImperativeHandle, useRef, forwardRef } from "react";
import { GLTF } from "three-stdlib";
import * as THREE from "three";
import type { Group } from 'three';
interface EarthModelProps extends React.ComponentProps<"group"> {
  scale: number;
}

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
  };
  materials: {
    ["Default OBJ"]: THREE.MeshStandardMaterial;
  };
};

export const EarthModel = forwardRef<Mesh | Group, EarthModelProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/earth.glb") as unknown as GLTFResult;
  const meshRef = useRef<Mesh>(null);

  useImperativeHandle(ref, () => meshRef.current!, []);

  const { ...rest } = props;

  return (
    <group {...rest} dispose={null}>
      <mesh
        ref={meshRef}
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Default OBJ"]}
        scale={props.scale}
      />
    </group>
  );
});

EarthModel.displayName = "EarthModel";

useGLTF.preload("/models/earth.glb");
