/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EarthModel(props) {
  const { nodes, materials } = useGLTF('/models/earth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Default OBJ']}
        scale={500}
      />
    </group>
  )
}

useGLTF.preload('/models/earth.glb')