/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const JupiterModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/models/jupiter.glb');

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref} 
        castShadow
        receiveShadow
        geometry={nodes['Node_#0'].geometry}
        material={materials.None}
        position={[-500, -467.563, -500]}
        scale={0.061}
      />
    </group>
  );
});

useGLTF.preload('/models/jupiter.glb');