/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SaturnModel(props) {
  const { nodes, materials } = useGLTF('/models/saturn.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1165.45, -451.019, -1165.45]} scale={0.142}>
        <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.None} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_0_1.geometry}
          material={materials.None}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/saturn.glb')